---
#In the hosts.ini file, added: 
# [ociarm:var]
# ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@BastionIP -i ~/.ssh/id_rsa.key"'
# This allows ssh passthrough through the main reverse proxy
- name: Install Kasm Workspaces on Oracle Cloud Free Tier (ARM)
  hosts: nodes
  become: true
  tasks:
      - name: Perform an update/dist upgrade
        ansible.builtin.apt:
          upgrade: dist
          update_cache: yes
      - name: Install Kasm
        ansible.builtin.shell: |
            cd /tmp
            curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.14.0.3a7abb.tar.gz
            tar -xf kasm_release_1.14.0.3a7abb.tar.gz
            sudo bash kasm_release/install.sh -y

### THIS IS CURRENTLY BROKEN! Need to accept and also set swap in the .sh file.